version: "3.7"

services:
    api:
        image: spotify-api
        container_name: api
        build: 
          context: ./api
          dockerfile: Dockerfile
        env_file:
            - ./api/.env
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./api:/api
            - /api/node_modules
        networks:
            - webappnetwork
    client:
        image: spotify-web
        container_name: web
        build: 
          context: ./web
          dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        networks:
            - webappnetwork
        depends_on:
            - api
networks:
    webappnetwork:
        driver: bridge
